## YAML Template.
server:
  port: 9001

spring:
  application:
     name: ZuulServer

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


zuul:
  routes:
    demo1:
      path: /microservicio2/**
      #url: http://localhost:9696/umg
      serviceId: microservicio2
    get:
      path: /desdenodejs/**
      serviceId: pruebanode
  host:
    socket-timeout-millis: 10000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:5001/eureka